openapi: 3.0.1
info:
   title: BIP Framework Specification
   description: BIP Framework objects for API services to generate code
components:
  securitySchemes:
    Authorization:
      type: apiKey
      name: Authorization
      in: header
    bearerAuth:
      type: http
      bearerFormat: JWT
      scheme: bearer
  schemas:
    Message:
      type: object
      required:
      - key
      - severity
      properties:
        key:
          type: string
        severity:
          type: string
        status:
          type: string
        text:
          type: string
        timestamp:
          type: string
          example: yyyy-MM-dd'T'HH:mm:ss.SSS
      title: Message
    Person:
      type: object
      properties:
        assuranceLevel:
          type: integer
          format: int32
          example: 2
          description: The person's access assurance level
        birthDate:
          type: string
          example: '1978-05-20'
          description: The person's birth date
        correlationIds:
          type: array
          example:
          - 77779102^NI^200M^USVHA^P
          - 912444689^PI^200BRLS^USVBA^A
          - 6666345^PI^200CORP^USVBA^A
          - 1105051936^NI^200DOD^USDOD^A
          - 912444689^SS
          description: The MVI correlation IDs list for the person
          items:
            type: string
        email:
          type: string
          example: jane.doe@va.gov
          description: The person's email address
        firstName:
          type: string
          example: JANE
          description: The person's first name
        gender:
          type: string
          example: FEMALE
          description: The person's gender
        lastName:
          type: string
          example: DOE
          description: The person's last name
        middleName:
          type: string
          example: M
          description: The person's middle name
        prefix:
          type: string
          example: Ms
          description: The prefix for the person's full name
        suffix:
          type: string
          example: S
          description: The suffix for the person's full name
        user:
          type: string
      title: Person
      description: Model that identifies a single individual used in the security context
    ProviderResponse: 
      type: object
      properties:
        messages:
          type: array
          items:
            '$ref': '#/components/schemas/Message'
      title: ProviderResponse
    ProviderRequest: 
      type: object
      title: ProviderRequest
    