openapi: 3.0.1
info:
   version: 1.0.1-SNAPSHOT
   title: BIP Reference Person Spring Boot Service v1 API Documentation
   description: A sample API that uses a petstore as an example to demonstrate features in the OpenAPI 3.0 specification
   termsOfService: https://developer.va.gov/terms-of-service
   license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
servers:
  - url: http://localhost:8080/api/v1
    description: Local server
tags:
  - name: reference-person
    description: Reference Person Resource
  - name: person-rest-client-tester
    description: Person Rest Client Tester
  - name: token-resource
    description: Token Resource
paths:
  "/persons/clientTests/callPersonByPidUsingFeignClient":
    post:
      tags:
      - person-rest-client-tester
      summary: An endpoint which uses a REST client using Feign to call the remote
        person by pid operation.
      operationId: callPersonByPidUsingFeignClientUsingPOST
      requestBody:
          description: personInfoRequest
          required: true
          content:
            application/json:
              schema:
                '$ref': '#/components/schemas/PersonInfoRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                '$ref': '#/components/schemas/PersonInfoResponse'
        '400':
          description: There was an error encountered processing the Request.  Response
            will contain a  "messages" element that will provide further information
            on the error.  This request shouldn't be retried until corrected.
          content:
            application/problem+json:
              schema:
                '$ref': './framework.yml#/components/schemas/ProviderResponse'
        '403':
          description: The request is not authorized.  Please verify credentials used
            in the request.
          content:
            application/problem+json:
              schema:
                '$ref': './framework.yml#/components/schemas/ProviderResponse'
        '500':
          description: There was an error encountered processing the Request.  Response
            will contain a  "messages" element that will provide further information
            on the error.  Please retry.  If problem persists, please contact support
            with a copy of the Response.
          content:
            application/problem+json:
              schema:
                '$ref': './framework.yml#/components/schemas/ProviderResponse'
      security:
        - bearerAuth: []
      deprecated: false
  "/persons/clientTests/callPersonByPidUsingRestTemplate":
    post:
      tags:
      - person-rest-client-tester
      summary: An endpoint which uses a REST client using RestTemplate to call the
        remote echo operation.
      operationId: callPersonByPidUsingRestTemplateUsingPOST
      requestBody:
        description: personInfoRequest
        required: true
        content:
            application/json:
              schema:
                '$ref': '#/components/schemas/PersonInfoRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                '$ref': '#/components/schemas/PersonInfoResponse'
        '400':
          description: There was an error encountered processing the Request.  Response
            will contain a  "messages" element that will provide further information
            on the error.  This request shouldn't be retried until corrected.
          content:
            application/problem+json:
              schema:
                '$ref': './framework.yml#/components/schemas/ProviderResponse'
        '403':
          description: The request is not authorized.  Please verify credentials used
            in the request.
          content:
            application/problem+json:
              schema:
                '$ref': './framework.yml#/components/schemas/ProviderResponse'
        '500':
          description: There was an error encountered processing the Request.  Response
            will contain a  "messages" element that will provide further information
            on the error.  Please retry.  If problem persists, please contact support
            with a copy of the Response.
          content:
            application/problem+json:
              schema:
                '$ref': './framework.yml#/components/schemas/ProviderResponse'
      security:
        - bearerAuth: []
      deprecated: false
  "/persons/pid":
    post:
      tags:
      - reference-person
      summary: Retrieve person information by PID from Person Service .
      description: Will return a person info object based on search by PID.
      operationId: personByPid
      requestBody: 
        description: personInfoRequest
        required: true
        content:
            application/json:
              schema:
                '$ref': '#/components/schemas/PersonInfoRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                '$ref': '#/components/schemas/PersonInfoResponse'
        '400':
          description: There was an error encountered processing the Request.  Response
            will contain a  "messages" element that will provide further information
            on the error.  This request shouldn't be retried until corrected.
          content:
            application/problem+json:
              schema:
                '$ref': './framework.yml#/components/schemas/ProviderResponse'
        '403':
          description: The request is not authorized.  Please verify credentials used
            in the request.
          content:
            application/problem+json:
              schema:
                '$ref': './framework.yml#/components/schemas/ProviderResponse'
        '500':
          description: There was an error encountered processing the Request.  Response
            will contain a  "messages" element that will provide further information
            on the error.  Please retry.  If problem persists, please contact support
            with a copy of the Response.
          content:
            application/problem+json:
              schema:
                '$ref': './framework.yml#/components/schemas/ProviderResponse'
      security:
        - bearerAuth: []
      deprecated: false
  "/token":
    post:
      tags:
      - token-resource
      summary: Get JWT Token
      description: Get a JWT bearer token with 'person' data. Include MVI correlationIds
        if required by the target API.
      operationId: getTokenUsingPOST
      requestBody: 
        description: |-
          Identity information for the authenticated user. CorrelationIds may be null or an empty array if the target API does not require it. Otherwise, correlationIds must be the list as retrieved from MVI: <table style=\"table-layout:auto;width:700px;text-align:left;background-color:#efefef;\"><tr><th>Common ID Name</th><th>Example ID</th><th>Type</th><th>Source</th><th>Issuer</th><th>Status</th><th </tr><tr><td>Participant ID (PID)</td><td>12345678</td><td>PI</td><td>200CORP</td><td>USVBA</td><td>A</td></tr><tr><td>File Number</td><td>123456789</td><td>PI</td><td>200BRLS</td><td>USVBA</td><td>A</td></tr><tr><td>ICN</td><td>1234567890V123456</td><td>NI</td><td>200M</td><td>USVHA</td><td>A</td></tr><tr><td>EDIPI / PNID</td><td>1234567890</td><td>NI</td><td>200DOD</td><td>USDOD</td><td>A</td></tr><tr><td>SSN</td><td>123456789</td><td>SS</td><td></td><td></td><td></td></tr></table>
        required: true
        content:
            application/json:
              schema:
                '$ref': './framework.yml#/components/schemas/Person'
      responses:
        '200':
          description: A Response which indicates a successful Request.  The Response
            may contain "messages" that could describe warnings or further information.
          content:
            text/plain:
              schema:
                type: string
        '400':
          description: There was an error encountered processing the Request.  Response
            will contain a  "messages" element that will provide further information
            on the error.  This request shouldn't be retried until corrected.
          content:
            application/problem+json:
              schema:
                '$ref': './framework.yml#/components/schemas/ProviderResponse'
        '403':
          description: The request is not authorized.  Please verify credentials used
            in the request.
          content:
            application/problem+json:
              schema:
                '$ref': './framework.yml#/components/schemas/ProviderResponse'
        '500':
          description: There was an error encountered processing the Request.  Response
            will contain a  "messages" element that will provide further information
            on the error.  Please retry.  If problem persists, please contact support
            with a copy of the Response.
          content:
            application/problem+json:
              schema:
                '$ref': './framework.yml#/components/schemas/ProviderResponse'
      deprecated: false
components:
  securitySchemes:
    Authorization:
      type: apiKey
      name: Authorization
      in: header
    bearerAuth:
      type: http
      bearerFormat: JWT
      scheme: bearer
  schemas:
    PersonInfo:
      type: object
      properties:
        fileNumber:
          type: string
          example: 912444689
          description: The persons file number
        firstName:
          type: string
          example: JANE
          description: The persons first name
        lastName:
          type: string
          example: DOE
          description: The persons last name
        middleName:
          type: string
          example: M
          description: The persons middle name
        participantId:
          type: integer
          format: int64
          example: 6666345
          description: The persons participant ID
        socSecNo:
          type: string
          example: 912444689
          description: The persons SSN
      title: PersonInfo
      description: Model for data contained in the response from the Person Service
    PersonInfoRequest:
      title: PersonInfoRequest
      description: Model for data to request person information from the Person Service
      allOf:
        - '$ref': './framework.yml#/components/schemas/ProviderRequest'
        - type: object
          properties:
            participantID:
              type: integer
              format: int64
              example: 6666345
              description: The Participant ID of the person for whom to retrieve data
              minimum: 1
              exclusiveMinimum: false
              required:
              - participantID
    PersonInfoResponse:
      title: PersonInfoResponse
      description: Model for the response from the Person Service
      allOf:
       - '$ref': './framework.yml#/components/schemas/ProviderResponse'
       - type: object
         # all other properties specific to PersonInfoResponse
         properties:
            personInfo:
              description: The object representing the person information
              '$ref': '#/components/schemas/PersonInfo'
    