version: "3.3"

services:
  
  # Fill this out once the dev team has their app code into the repo
  os-reference-service:
    image: bip/os-reference-service
    build:
      context: ./os-reference-service-1
    environment:
      - spring.profiles.active=local-int
      - spring.cloud.consul.host=consul
      - spring.cloud.vault.host=vault
      - spring.cloud.consul.discovery.acl-token=7652ba4c-0f6e-8e75-5724-5e083d72cfe4
    ports:
      - "8080:8080"
    networks:
       - bip
    depends_on:
      - consul
      - redis
      - vault

  consul:
    image: consul
    ports:
      - "8500:8500"
    volumes: 
      - "./local-dev/consul/acl.json:/consul/config/acl.json"
    networks:
      - bip

  vault:
    image: vault
    ports:
      - "8200:8200"
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=${VAULT_TOKEN:-vaultroot}
    networks:
      - bip

  vault-config:
    image: bip/vault-config
    build:
      context: ./local-dev/vault-config
    environment:
      - VAULT_ADDR=http://vault:8200
      - VAULT_DEV_ROOT_TOKEN_ID=${VAULT_TOKEN:-vaultroot}
      - CONSUL_HTTP_ADDR=http://consul:8500
      - CONSUL_HTTP_TOKEN=7652ba4c-0f6e-8e75-5724-5e083d72cfe4
    networks:
      - bip

  redis:
    image: redis
    networks:
      - bip

networks:
  bip:
    driver: bridge