openapi: 3.0.1
info:
  version: 0.0.1-SNAPSHOT
  title: BIP Reference Person Spring Boot Service v1 API Documentation
servers:
  - url: http://localhost:8080/
    description: Local server
tags:
  - name: person-resource
    description: Person Resource
  - name: person-rest-client-tester
    description: Person Rest Client Tester
  - name: token-resource
    description: Token Resource
paths:
  "/api/v1/persons/clientTests/callPersonByPidUsingFeignClient":
    post:
      tags:
      - person-rest-client-tester
      summary: An endpoint which uses a REST client using Feign to call the remote
        person by pid operation.
      operationId: callPersonByPidUsingFeignClientUsingPOST
      requestBody:
          description: personInfoRequest
          required: true
          content:
            application/json:
              schema:
                "$ref": "#/definitions/PersonInfoRequest"
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                "$ref": "#/definitions/PersonInfoResponse"
        '400':
          description: There was an error encountered processing the Request.  Response
            will contain a  "messages" element that will provide further information
            on the error.  This request shouldn't be retried until corrected.
          content:
            application/json:
              schema:
                "$ref": "#/definitions/ProviderResponse"
        '403':
          description: The request is not authorized.  Please verify credentials used
            in the request.
          content:
            application/json:
              schema:
                "$ref": "#/definitions/ProviderResponse"
        '500':
          description: There was an error encountered processing the Request.  Response
            will contain a  "messages" element that will provide further information
            on the error.  Please retry.  If problem persists, please contact support
            with a copy of the Response.
          content:
            application/json:
              schema:
                "$ref": "#/definitions/ProviderResponse"
      security:
      - Authorization:
        - global
      deprecated: false
  "/api/v1/persons/clientTests/callPersonByPidUsingRestTemplate":
    post:
      tags:
      - person-rest-client-tester
      summary: An endpoint which uses a REST client using RestTemplate to call the
        remote echo operation.
      operationId: callPersonByPidUsingRestTemplateUsingPOST
      requestBody:
        description: personByPidDomainRequest
        required: true
        content:
            application/json:
              schema:
                "$ref": "#/definitions/PersonByPidDomainRequest"
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                "$ref": "#/definitions/PersonByPidDomainResponse"
        '400':
          description: There was an error encountered processing the Request.  Response
            will contain a  "messages" element that will provide further information
            on the error.  This request shouldn't be retried until corrected.
          content:
            application/json:
              schema:
                "$ref": "#/definitions/ProviderResponse"
        '403':
          description: The request is not authorized.  Please verify credentials used
            in the request.
          content:
            application/json:
              schema:
                "$ref": "#/definitions/ProviderResponse"
        '500':
          description: There was an error encountered processing the Request.  Response
            will contain a  "messages" element that will provide further information
            on the error.  Please retry.  If problem persists, please contact support
            with a copy of the Response.
          content:
            application/json:
              schema:
                "$ref": "#/definitions/ProviderResponse"
      security:
      - Authorization:
        - global
      deprecated: false
  "/api/v1/persons/health":
    get:
      tags:
      - person-resource
      summary: A health check of this endpoint
      description: Will perform a basic health check to see if the operation is running.
      operationId: healthUsingGET
      responses:
        '200':
          description: A Response which indicates a successful Request.  The Response
            may contain "messages" that could describe warnings or further information.
          content:
            application/json:
              schema:
                "$ref": "#/definitions/Health"
        '400':
          description: There was an error encountered processing the Request.  Response
            will contain a  "messages" element that will provide further information
            on the error.  This request shouldn't be retried until corrected.
          content:
            application/json:
              schema:
                "$ref": "#/definitions/ProviderResponse"
        '403':
          description: The request is not authorized.  Please verify credentials used
            in the request.
          content:
            application/json:
              schema:
                "$ref": "#/definitions/ProviderResponse"
        '500':
          description: There was an error encountered processing the Request.  Response
            will contain a  "messages" element that will provide further information
            on the error.  Please retry.  If problem persists, please contact support
            with a copy of the Response.
          content:
            application/json:
              schema:
                "$ref": "#/definitions/ProviderResponse"
      security:
      - Authorization:
        - global
      deprecated: false
  "/api/v1/persons/pid":
    post:
      tags:
      - person-resource
      summary: Retrieve person information by PID from Person Service .
      description: Will return a person info object based on search by PID.
      operationId: personByPidUsingPOST
      requestBody: 
        description: personInfoRequest
        required: true
        content:
            application/json:
              schema:
                "$ref": "#/definitions/PersonInfoRequest"
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                "$ref": "#/definitions/PersonInfoResponse"
        '400':
          description: There was an error encountered processing the Request.  Response
            will contain a  "messages" element that will provide further information
            on the error.  This request shouldn't be retried until corrected.
          content:
            application/json:
              schema:
                "$ref": "#/definitions/ProviderResponse"
        '403':
          description: The request is not authorized.  Please verify credentials used
            in the request.
          content:
            application/json:
              schema:
                "$ref": "#/definitions/ProviderResponse"
        '500':
          description: There was an error encountered processing the Request.  Response
            will contain a  "messages" element that will provide further information
            on the error.  Please retry.  If problem persists, please contact support
            with a copy of the Response.
          content:
            application/json:
              schema:
                "$ref": "#/definitions/ProviderResponse"
      security:
      - Authorization:
        - global
      deprecated: false
  "/token":
    post:
      tags:
      - token-resource
      summary: Get JWT Token
      description: Get a JWT bearer token with 'person' data. Include MVI correlationIds
        if required by the target API.
      operationId: getTokenUsingPOST
      requestBody: 
        description: |-
          Identity information for the authenticated user. CorrelationIds may be null or an empty array if the target API does not require it. Otherwise, correlationIds must be the list as retrieved from MVI:
          <table style="table-layout:auto;width:700px;text-align:left;background-color:#efefef;"><tr><th>Common ID Name</th><th>Example ID</th><th>Type</th><th>Source</th><th>Issuer</th><th>Status</th><th </tr><tr><td>Participant ID (PID)</td><td>12345678</td><td>PI</td><td>200CORP</td><td>USVBA</td><td>A</td></tr><tr><td>File Number</td><td>123456789</td><td>PI</td><td>200BRLS</td><td>USVBA</td><td>A</td></tr><tr><td>ICN</td><td>1234567890V123456</td><td>NI</td><td>200M</td><td>USVHA</td><td>A</td></tr><tr><td>EDIPI / PNID</td><td>1234567890</td><td>NI</td><td>200DOD</td><td>USDOD</td><td>A</td></tr><tr><td>SSN</td><td>123456789</td><td>SS</td><td></td><td></td><td></td></tr></table>
        required: true
        content:
            application/json:
              schema:
                "$ref": "#/definitions/Person"
      responses:
        '200':
          description: A Response which indicates a successful Request.  The Response
            may contain "messages" that could describe warnings or further information.
          content:
            application/json:
              schema:
                type: string
        '400':
          description: There was an error encountered processing the Request.  Response
            will contain a  "messages" element that will provide further information
            on the error.  This request shouldn't be retried until corrected.
          content:
            application/json:
              schema:
                "$ref": "#/definitions/ProviderResponse"
        '403':
          description: The request is not authorized.  Please verify credentials used
            in the request.
          content:
            application/json:
              schema:
                "$ref": "#/definitions/ProviderResponse"
        '500':
          description: There was an error encountered processing the Request.  Response
            will contain a  "messages" element that will provide further information
            on the error.  Please retry.  If problem persists, please contact support
            with a copy of the Response.
          content:
            application/json:
              schema:
                "$ref": "#/definitions/ProviderResponse"
      deprecated: false
components:
  securitySchemes:
    Authorization:
      type: apiKey
      name: Authorization
      in: header
  schemas:
    Health:
      type: object
      properties:
        description:
          type: string
        details:
          type: object
        status:
          type: string
      title: Health
    Message:
      type: object
      required:
      - key
      - severity
      properties:
        key:
          type: string
        severity:
          type: string
        status:
          type: string
        text:
          type: string
        timestamp:
          type: string
          example: yyyy-MM-dd'T'HH:mm:ss.SSS
      title: Message
    Person:
      type: object
      properties:
        assuranceLevel:
          type: integer
          format: int32
          example: 2
          description: The person's access assurance level
        birthDate:
          type: string
          example: '1978-05-20'
          description: The person's birth date
        correlationIds:
          type: array
          example:
          - 77779102^NI^200M^USVHA^P
          - 912444689^PI^200BRLS^USVBA^A
          - 6666345^PI^200CORP^USVBA^A
          - 1105051936^NI^200DOD^USDOD^A
          - 912444689^SS
          description: The MVI correlation IDs list for the person
          items:
            type: string
        email:
          type: string
          example: jane.doe@va.gov
          description: The person's email address
        firstName:
          type: string
          example: JANE
          description: The person's first name
        gender:
          type: string
          example: FEMALE
          description: The person's gender
        lastName:
          type: string
          example: DOE
          description: The person's last name
        middleName:
          type: string
          example: M
          description: The person's middle name
        prefix:
          type: string
          example: Ms
          description: The prefix for the person's full name
        suffix:
          type: string
          example: S
          description: The suffix for the person's full name
        user:
          type: string
      title: Person
      description: Model that identifies a single individual used in the security context
    PersonByPidDomainRequest:
      type: object
      required:
      - participantID
      properties:
        participantID:
          type: integer
          format: int64
          example: 6666345
          description: The Participant ID of the person for whom to retrieve data
      title: PersonByPidDomainRequest
      xml:
        name: serviceRequest
        attribute: false
        wrapped: false
    PersonByPidDomainResponse:
      type: object
      properties:
        messages:
          type: array
          items:
            "$ref": "#/definitions/ServiceMessage"
        personInfo:
          "$ref": "#/definitions/PersonInfoDomain"
      title: PersonByPidDomainResponse
    PersonInfo:
      type: object
      properties:
        fileNumber:
          type: string
          example: 912444689
          description: The persons file number
        firstName:
          type: string
          example: JANE
          description: The persons first name
        lastName:
          type: string
          example: DOE
          description: The persons last name
        middleName:
          type: string
          example: M
          description: The persons middle name
        participantId:
          type: integer
          format: int64
          example: 6666345
          description: The persons participant ID
        socSecNo:
          type: string
          example: 912444689
          description: The persons SSN
      title: PersonInfo
      description: Model for data contained in the response from the Person Service
    PersonInfoDomain:
      type: object
      properties:
        fileNumber:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        middleName:
          type: string
        participantId:
          type: integer
          format: int64
        socSecNo:
          type: string
      title: PersonInfoDomain
    PersonInfoRequest:
      type: object
      required:
      - participantID
      properties:
        participantID:
          type: integer
          format: int64
          example: 6666345
          description: The Participant ID of the person for whom to retrieve data
          minimum: 1
          exclusiveMinimum: false
      title: PersonInfoRequest
      description: Model for data to request PersonInfoDomain from the Person Service
    PersonInfoResponse:
      type: object
      properties:
        messages:
          type: array
          items:
            "$ref": "#/definitions/Message"
        personInfo:
          description: The object representing the person information
          "$ref": "#/definitions/PersonInfo"
      title: PersonInfoResponse
      description: Model for the response from the Person Service
    ProviderResponse:
      type: object
      properties:
        messages:
          type: array
          items:
            "$ref": "#/definitions/Message"
      title: ProviderResponse
    ServiceMessage:
      type: object
      required:
      - key
      - severity
      properties:
        key:
          type: string
          xml:
            name: key
            attribute: false
            wrapped: false
        severity:
          type: string
          xml:
            name: severity
            attribute: false
            wrapped: false
          enum:
          - TRACE
          - DEBUG
          - INFO
          - WARN
          - ERROR
          - FATAL
        status:
          type: string
        text:
          type: string
        timestamp:
          type: string
          example: yyyy-MM-dd'T'HH:mm:ss.SSS
      title: ServiceMessage
