version: "3.3"

services:
  
  # Fill this out once the dev team has their app code into the repo
  ocp-vetservices-claims:
    image: ocpdev/ocp-vetservices-claims
    build:
      context: ./
    environment:
      - spring.profiles.active=local-int
      - spring.cloud.consul.host=consul
      - spring.redis.host=redis
      - spring.cloud.vault.host=vault
      - spring.cloud.consul.config.enabled=true
      - spring.cloud.consul.config.failFast=true
      - spring.cloud.consul.discovery.enabled=true
      - spring.cloud.consul.discovery.register=true
      - spring.cloud.vault.enabled=true
      - spring.cloud.vault.consul.enabled=true
      - ocp.security.jwt.enabled=true
    ports:
      - "8080:8080"
    networks:
       - bip

networks:
  bip:
    driver: bridge