scrape_configs:
  - job_name: 'app_metrics'

    consul_sd_configs:
    - server: 'consul:8500'
      scheme: 'http'
      token: '7652ba4c-0f6e-8e75-5724-5e083d72cfe4'
      services: ['os-reference-service-1']

    scrape_interval: 5s
    scheme: http
    metrics_path: /actuator/prometheus
  